-- Menu table

INSERT INTO menu (Menu_ID, Client_ID, Language, Menu_Name, Display_Order, Parent_Menu_ID, Action, Header_Message) VALUES
('1', '1', 'ENG', 'Book Appointment', '1', '0', NULL, '*How can I help you?*'),
('2', '1', 'ENG', 'Reschedule', '2', '0', NULL, NULL),
('3', '1', 'ENG', 'Cancel Appointment', '3', '0', NULL, NULL),
('4', '1', 'ENG', 'Emergency', '1', '1', NULL, NULL),
('5', '1', 'ENG', 'Tele Consultation', '2', '1', NULL, NULL),
('6', '1', 'ENG', 'Direct Consultation', '3', '1', NULL, NULL),
('7', '1', 'ENG', 'Master Health Checkup', '4', '1', NULL, NULL),
('8', '1', 'ENG', 'Select Date Checkup', '1', '7', 'Appointment_Type~FETCH_AVAILABLE_DATES_CHECKUP', 'Select a date'),
('9', '1', 'ENG', 'Select Time Checkup', '1', '8', 'Appointment_Date~FETCH_AVAILABLE_TIMES_DIRECT', 'Select a time'),
('10', '1', 'ENG', 'Confirm Checkup Appointment', '1', '9', 'Appointment_Time~CONFIRM~CONFIRM_CHECKUP', 'Please Confirm Your details'),
('11', '1', 'ENG', 'Finalize Checkup Appointment', '1', '10', 'Confirm_Status~FINALIZE~FINALIZE_CHECKUP', 'Appointment is confirmed'),
('12', '1', 'ENG', 'Show Emergency Reasons List', '1', '4', 'Appointment_Type~LIST~EMERGENCY_REASON', 'Select the Emergency Reason'),
('13', '1', 'ENG', 'Confirm Emergency Details', '1', '12', 'Emergency_Reason~CONFIRM~CONFIRM_EMERGENCY', 'Please Confirm Your details'),
('14', '1', 'ENG', 'Finalize Emergency', '1', '13', 'Confirm_Status~FINALIZE~FINALIZE_EMERGENCY', 'Waiting for your arrival'),
('15', '1', 'ENG', 'Show Department List', '1', '6', 'Appointment_Type~LIST~DEPARTMENT', 'Select the Department'),
('16', '1', 'ENG', 'Select Doctor Direct', '1', '15', 'Department~POC~Specialization', 'Select the doctor'),
('17', '1', 'ENG', 'Select Date Direct', '1', '16', 'Poc_name~FETCH_AVAILABLE_DATES_DIRECT', 'Select the date'),
('18', '1', 'ENG', 'Select Time Direct', '1', '17', 'Appointment_Date~FETCH_AVAILABLE_TIMES_DIRECT', 'Select the time'),
('19', '1', 'ENG', 'Confirm Direct Appointment', '1', '18', 'Appointment_Time~CONFIRM~CONFIRM_DIRECT', 'Please confirm your details.'),
('20', '1', 'ENG', 'Finalize Direct Appointment', '1', '19', 'Confirm_Status~FINALIZE~FINALIZE_DIRECT', 'Appointment confirmed.Your Appointment ID: [Appointment_ID]'),
('21', '1', 'ENG', 'Select Department Tele', '1', '5', 'Appointment_Type~LIST~DEPARTMENT', 'Select a department'),
('22', '1', 'ENG', 'Select Doctor Tele', '1', '21', 'Department~POC~DEPARTMENT_ID', 'Select a doctor'),
('23', '1', 'ENG', 'Select Date Tele', '1', '22', 'Poc_name~FETCH_AVAILABLE_DATES_DIRECT', 'Select a date'),
('24', '1', 'ENG', 'Select Time Tele', '1', '23', 'Appointment_Date~FETCH_AVAILABLE_TIMES_DIRECT', 'Select a time'),
('25', '1', 'ENG', 'Confirm Tele Appointment', '1', '24', 'Appointment_Time~CONFIRM~CONFIRM_TELE', 'Please confirm your appointment details'),
('26', '1', 'ENG', 'Finalize Tele Appointment', '1', '25', 'Confirm_Status~FINALIZE~FINALIZE_TELE', 'Your gmeet link is given below'),
('27', '1', 'ENG', 'Confirm Cancel', '1', '3', 'Appointment_Function~FETCH_APPOINTMENT_DETAILS', 'Cancel your appointment'),
('28', '1', 'ENG', 'Finalize Cancel', '1', '27', 'Confirm_Status~FINALIZE_CANCEL', 'Appointment Cancelled'),
('29', '1', 'ENG', 'Fetch Appointment Details', '1', '2', 'Appointment_Function~FETCH_APPOINTMENT_DETAILS_RESCHEDULE', 'Reschedule your appointment'),
('30', '1', 'ENG', 'Fetch available Dates', '1', '29', 'Confirm_Status~RESCHEDULE_DATE', 'Select a new date'),
('31', '1', 'ENG', 'Fetch available Time', '1', '30', 'Appointment_Date~FETCH_AVAILABLE_TIMES_DIRECT', 'Select a time'),
('32', '1', 'ENG', 'Confirm Reschedule', '1', '31', 'Appointment_Time~CONFIRM_RESCHEDULE', 'Reschedule your appointment'),
('33', '1', 'ENG', 'Finalize Reschedule', '1', '32', 'Confirm_Status~FINALIZE_RESCHEDULE', 'Appointment Rescheduled'),
('34', '2', 'ENG', 'Book Appointment ', '1', '0', NULL, '*How can I help you?*'),
('35', '2', 'ENG', 'Fetch Doctor', '1', '34', 'Appointment_Function~POC~Specialization', 'Select a Doctor'),
('36', '2', 'ENG', 'Fetch Dates', '1', '35', 'Poc_name~FETCH_AVAILABLE_DATES_DIRECT', 'Select a date'),
('37', '2', 'ENG', 'Fetch Times', '1', '36', 'Appointment_Date~FETCH_AVAILABLE_TIMES_DIRECT', 'Select a time'),
('38', '2', 'ENG', 'Confirm', '1', '37', 'Appointment_Time~CONFIRM~CONFIRM', 'Please confirm your details'),
('39', '2', 'ENG', 'Finalize', '1', '38', 'Confirm_Status~FINALIZE~FINALIZE', 'Appointment Confirmed');
